"""Description of changes

Revision ID: 221abf8115a0
Revises: 
Create Date: 2024-08-31 12:52:32.755212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '221abf8115a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_licenses_id', table_name='licenses')
    op.drop_table('licenses')
    op.drop_index('ix_equipements_equipement_id', table_name='equipements')
    op.drop_table('equipements')
    op.drop_index('ix_employee_id', table_name='employee')
    op.drop_table('employee')
    op.drop_index('ix_hyperviseur_id', table_name='hyperviseur')
    op.drop_table('hyperviseur')
    op.drop_index('ix_employee_equipement_association_id', table_name='employee_equipement_association')
    op.drop_table('employee_equipement_association')
    op.drop_index('ix_clusters_id', table_name='clusters')
    op.drop_table('clusters')
    op.drop_index('ix_acquisition_num_acquisition', table_name='acquisition')
    op.drop_table('acquisition')
    op.drop_index('ix_contrat_id', table_name='contrat')
    op.drop_table('contrat')
    op.drop_index('ix_machines_virtuelles_id_vm', table_name='machines_virtuelles')
    op.drop_table('machines_virtuelles')
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_applications_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('acquisition_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.num_acquisition'], name='FK__events__acquisit__7A672E12'),
    sa.PrimaryKeyConstraint('id', name='PK__events__3213E83F1F90C822')
    )
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255, collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password_hashed', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__users__3213E83F2A58ADCD')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('responsable', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('serveur_physique_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('machine_virtuelle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_license', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_license'], ['licenses.id'], name='FK__applicati__id_li__22751F6C'),
    sa.ForeignKeyConstraint(['machine_virtuelle_id'], ['machines_virtuelles.id_vm'], name='FK__applicati__machi__2180FB33'),
    sa.ForeignKeyConstraint(['serveur_physique_id'], ['equipements.equipement_id'], name='FK__applicati__serve__208CD6FA'),
    sa.PrimaryKeyConstraint('id', name='PK__applicat__3213E83F8D7287B1')
    )
    op.create_index('ix_applications_id', 'applications', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('service', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__employee__3213E83F848227A5')
    )
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.create_table('machines_virtuelles',
    sa.Column('id_vm', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('stockage', sa.VARCHAR(length=50, collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ram', sa.VARCHAR(length=50, collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.VARCHAR(length=50, collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('hyperviseur_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(length=255, collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name='FK__machines___clust__6E01572D'),
    sa.ForeignKeyConstraint(['hyperviseur_id'], ['hyperviseur.id'], name='FK__machines___hyper__6D0D32F4'),
    sa.PrimaryKeyConstraint('id_vm', name='PK__machines__0148708C8E435CF2')
    )
    op.create_index('ix_machines_virtuelles_id_vm', 'machines_virtuelles', ['id_vm'], unique=False)
    op.create_table('contrat',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('num_contrat', sa.VARCHAR(length=255, collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('dateAchat', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('dateExpiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('montant', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('fournisseur', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__contrat__3213E83F93CB5F1F')
    )
    op.create_index('ix_contrat_id', 'contrat', ['id'], unique=False)
    op.create_table('acquisition',
    sa.Column('num_acquisition', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('budget', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('dateAchat', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fournisseur', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('statut', sa.NVARCHAR(length=255, collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('contrat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrat.id'], name='FK__acquisiti__contr__5FB337D6'),
    sa.PrimaryKeyConstraint('num_acquisition', name='PK__acquisit__8DB187F9C3A4751B')
    )
    op.create_index('ix_acquisition_num_acquisition', 'acquisition', ['num_acquisition'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__clusters__3213E83F1CBF8B7F')
    )
    op.create_index('ix_clusters_id', 'clusters', ['id'], unique=False)
    op.create_table('employee_equipement_association',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('status', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('date_affectation', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_desaffectation', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='FK__employee___emplo__66603565'),
    sa.ForeignKeyConstraint(['equipement_id'], ['equipements.equipement_id'], name='FK__employee___equip__6754599E'),
    sa.PrimaryKeyConstraint('id', name='PK__employee__3213E83F81B73072')
    )
    op.create_index('ix_employee_equipement_association_id', 'employee_equipement_association', ['id'], unique=False)
    op.create_table('hyperviseur',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('serveur_physique_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['serveur_physique_id'], ['equipements.equipement_id'], name='FK__hypervise__serve__6A30C649'),
    sa.PrimaryKeyConstraint('id', name='PK__hypervis__3213E83F1ED8C1CC')
    )
    op.create_index('ix_hyperviseur_id', 'hyperviseur', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('matricule', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('service', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__employee__3213E83F2C667ADE')
    )
    op.create_index('ix_employee_id', 'employee', ['id'], unique=False)
    op.create_table('equipements',
    sa.Column('equipement_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('adresse_ip', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('num_serie', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codeBar', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('marque', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('modele', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dateMiseService', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rackable', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('responsable', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('systemeInstalle', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('nombreUniteOccRack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombreLecteur', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombreBonde', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stockage', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ram', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refAchat', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('numContratMaint', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prestataireMaintenance', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dateDebutMaintenance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dateFinMaintenance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('typeMaintenance', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_acquisition', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantite', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name='FK__equipemen__clust__628FA481'),
    sa.ForeignKeyConstraint(['num_acquisition'], ['acquisition.num_acquisition'], name='FK__equipemen__num_a__6383C8BA'),
    sa.PrimaryKeyConstraint('equipement_id', name='PK__equipeme__BBCA6F2F348A5126')
    )
    op.create_index('ix_equipements_equipement_id', 'equipements', ['equipement_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('dateDebut', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('dateExpiration', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('nombreUtilisations', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('utilisationsRestantes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fournisseur', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('cout', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('renouvellementAutomatique', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('dateRenouvellement', sa.VARCHAR(collation='French_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__licenses__3213E83F8EDA45CE')
    )
    op.create_index('ix_licenses_id', 'licenses', ['id'], unique=False)
    # ### end Alembic commands ###
